In [ ]:
import pandas as pd

df = pd.read_excel("Raw_Data_Cleaning_Project.xlsx")

df.head()

   Employee_ID     Name Age         City   Join_Date   Salary Department
0         1001   Balaji  33      Chennai  2022-01-16  28000.0         HR
1         1002  Karthik  31   bengaluru   2022-01-14  27000.0    Support
2         1003   Balaji  27    Hyderabad  17/02/2023  27000.0         IT
3         1004     Arun  40      madurai  2022/11/08  70000.0         IT
4         1005    Divya  44   bengaluru   18/05/2022  31000.0         HR

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Employee_ID  100 non-null    int64
 1   Name         100 non-null    object
 2   Age          99 non-null     object
 3   City         99 non-null     object
 4   Join_Date    99 non-null     object
 5   Salary       99 non-null     float64
 6   Department   100 non-null    object
dtypes: float64(1), int64(1), object(5)
memory usage: 5.6+ KB

In [ ]:
df.isnull().sum()

Employee_ID    0
Name           0
Age            1
City           1
Join_Date      1
Salary         1
Department     0
dtype: int64

In [ ]:
df[df.isnull().any(axis=1)]

    Employee_ID     Name  Age         City   Join_Date   Salary Department
5          1006  Karthik  NaN      madurai  01/06/2022  64000.0         IT
10         1011    Meena   33   bengaluru          NaN  65000.0    Finance
50         1051    Meena   39    Hyderabad  2022/04/09      NaN      Sales
60         1061   Anitha   41          NaN  05-02-2022  46000.0      Sales

In [ ]:
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")

In [ ]:
df["Age"].fillna(df["Age"].median(), inplace=True)

/tmp/ipykernel_945/2097741607.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(df["Age"].median(), inplace=True)

In [ ]:
df["City"].fillna(df["City"].mode()[0], inplace=True)

/tmp/ipykernel_945/442806574.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["City"].fillna(df["City"].mode()[0], inplace=True)

In [ ]:
df["Join_Date"].fillna(method="ffill", inplace=True)

/tmp/ipykernel_945/1559719935.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Join_Date"].fillna(method="ffill", inplace=True)
/tmp/ipykernel_945/1559719935.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Join_Date"].fillna(method="ffill", inplace=True)

In [ ]:
df.isnull().sum()

Employee_ID    0
Name           0
Age            0
City           0
Join_Date      0
Salary         0
Department     0
dtype: int64

In [ ]:
df["Salary"].fillna(df["Salary"].median(), inplace=True)

/tmp/ipykernel_945/2465791117.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Salary"].fillna(df["Salary"].median(), inplace=True)

In [ ]:
df.duplicated().sum()

np.int64(1)

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df[df.duplicated(subset="Employee_ID", keep=False)]

    Employee_ID    Name   Age       City   Join_Date   Salary Department
39         1040   Divya  41.0  Hyderabad  14/02/2024  70000.0    Support
40         1040  Anitha  39.0     mumbai  2022/02/27  31000.0    Support

In [ ]:
df.drop_duplicates(subset="Employee_ID", keep="first", inplace=True)

In [ ]:
df["Employee_ID"].duplicated().sum()

np.int64(0)

In [ ]:
df["Name"] = df["Name"].str.strip()
df["City"] = df["City"].str.strip()

In [ ]:
df["Name"] = df["Name"].str.title()

In [ ]:
df["City"] = df["City"].str.title()

In [ ]:
df["Salary"] = df["Salary"].round(2)

In [ ]:
df.to_excel("Cleaned_Data.xlsx", index=False)

In [ ]:
df.head(10)

   Employee_ID     Name   Age        City   Join_Date   Salary Department
0         1001   Balaji  33.0     Chennai  2022-01-16  28000.0         HR
1         1002  Karthik  31.0   Bengaluru  2022-01-14  27000.0    Support
2         1003   Balaji  27.0   Hyderabad  17/02/2023  27000.0         IT
3         1004     Arun  40.0     Madurai  2022/11/08  70000.0         IT
4         1005    Divya  44.0   Bengaluru  18/05/2022  31000.0         HR
5         1006  Karthik  36.0     Madurai  01/06/2022  64000.0         IT
6         1007  Vignesh  43.0   Hyderabad  2022-09-16  45000.0         IT
7         1008    Sneha  33.0  Coimbatore  07/06/2023  74000.0    Support
8         1009   Balaji  43.0      Mumbai  15/03/2023  59000.0         HR
9         1010   Balaji  33.0   Hyderabad  2022/07/16  43000.0         IT

In [ ]:
df["Join_Date"] = pd.to_datetime(df["Join_Date"], format="mixed", dayfirst=True, errors="coerce")

In [ ]:
df["Join_Date"] = df["Join_Date"].dt.strftime("%Y-%m-%d")

In [ ]:
df.head(10)

   Employee_ID     Name   Age        City   Join_Date   Salary Department
0         1001   Balaji  33.0     Chennai  2022-01-16  28000.0         HR
1         1002  Karthik  31.0   Bengaluru  2022-01-14  27000.0    Support
2         1003   Balaji  27.0   Hyderabad  2023-02-17  27000.0         IT
3         1004     Arun  40.0     Madurai  2022-11-08  70000.0         IT
4         1005    Divya  44.0   Bengaluru  2022-05-18  31000.0         HR
5         1006  Karthik  36.0     Madurai  2022-06-01  64000.0         IT
6         1007  Vignesh  43.0   Hyderabad  2022-09-16  45000.0         IT
7         1008    Sneha  33.0  Coimbatore  2023-06-07  74000.0    Support
8         1009   Balaji  43.0      Mumbai  2023-03-15  59000.0         HR
9         1010   Balaji  33.0   Hyderabad  2022-07-16  43000.0         IT

In [ ]:
df.head(10)

   Employee_ID     Name   Age        City   Join_Date   Salary Department
0         1001   Balaji  33.0     Chennai  2022-01-16  28000.0         HR
1         1002  Karthik  31.0   Bengaluru  2022-01-14  27000.0    Support
2         1003   Balaji  27.0   Hyderabad  2023-02-17  27000.0         IT
3         1004     Arun  40.0     Madurai  2022-11-08  70000.0         IT
4         1005    Divya  44.0   Bengaluru  2022-05-18  31000.0         HR
5         1006  Karthik  36.0     Madurai  2022-06-01  64000.0         IT
6         1007  Vignesh  43.0   Hyderabad  2022-09-16  45000.0         IT
7         1008    Sneha  33.0  Coimbatore  2023-06-07  74000.0    Support
8         1009   Balaji  43.0      Mumbai  2023-03-15  59000.0         HR
9         1010   Balaji  33.0   Hyderabad  2022-07-16  43000.0         IT

In [ ]:
print("Missing Values:")
print(df.isnull().sum())

print("\nDuplicate Rows:")
print(df.duplicated().sum())

print("\nDuplicate Employee IDs:")
print(df["Employee_ID"].duplicated().sum())

print("\nData Types:")
print(df.dtypes)

Missing Values:
Employee_ID    0
Name           0
Age            0
City           0
Join_Date      1
Salary         0
Department     0
dtype: int64

Duplicate Rows:
0

Duplicate Employee IDs:
0

Data Types:
Employee_ID      int64
Name            object
Age            float64
City            object
Join_Date       object
Salary         float64
Department      object
dtype: object

df["Join_Date"] = pd.to_datetime(
    df["Join_Date"],
    format="mixed",
    dayfirst=True,
    errors="coerce"
)

In [ ]:
df[df["Join_Date"].isnull()]

    Employee_ID   Name   Age       City Join_Date   Salary Department
70         1071  Meena  39.0  Hyderabad       NaT  34000.0      Sales

In [ ]:
df["Join_Date"] = df["Join_Date"].fillna(method="ffill")

/tmp/ipykernel_945/2526979697.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Join_Date"] = df["Join_Date"].fillna(method="ffill")

In [ ]:
df["Join_Date"] = df["Join_Date"].ffill()

df.isnull().sum()

In [ ]:
df.to_excel("Cleaned_Data.xlsx", index=False)

df.to_csv("Cleaned_Data.csv", index=False)